### ISSUE TITLE
DFA Reporting Sample

### ISSUE THREAD

**Issue by anjanjena** [googleads/googleads-dfa-reporting-samples#8]
Hi this is Anjan,

I was trying to download a report using this example by running the file called DownloadFile.java ,
I have followed all the instruction written there but not able to run this code sucessfuly. 
Please find the below exception which i am getting :-

Aug 30, 2016 2:31:42 PM com.google.api.client.util.store.FileDataStoreFactory setPermissionsToOwnerOnly
WARNING: unable to change permissions for everybody: D:\Users\703169350\.store\dfareporting_sample
Aug 30, 2016 2:31:42 PM com.google.api.client.util.store.FileDataStoreFactory setPermissionsToOwnerOnly
WARNING: unable to change permissions for owner: D:\Users\703169350\.store\dfareporting_sample
2016-08-30 14:37:31.436:INFO::Logging to STDERR via org.mortbay.log.StdErrLog
2016-08-30 14:37:31.444:INFO::jetty-6.1.26
2016-08-30 14:37:31.644:INFO::Started SocketConnector@localhost:54447
Please open the following address in your browser:
  https://accounts.google.com/o/oauth2/auth?client_id=346983687935-4e58re1q7lbgl6o07c8h699m3fn5jau4.apps.googleusercontent.com&redirect_uri=http://localhost:54447/Callback&response_type=code&scope=https://www.googleapis.com/auth/dfareporting%20https://www.googleapis.com/auth/dfatrafficking%20https://www.googleapis.com/auth/ddmconversions
Attempting to open that address in the default browser now...
2016-08-30 15:03:13.717:INFO::Stopped SocketConnector@localhost:54447
Exception in thread "main" java.net.SocketTimeoutException: connect timed out
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(Unknown Source)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:77)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:981)
	at com.google.api.client.auth.oauth2.TokenRequest.executeUnparsed(TokenRequest.java:283)
	at com.google.api.client.googleapis.auth.oauth2.GoogleAuthorizationCodeTokenRequest.execute(GoogleAuthorizationCodeTokenRequest.java:158)
	at com.google.api.client.googleapis.auth.oauth2.GoogleAuthorizationCodeTokenRequest.execute(GoogleAuthorizationCodeTokenRequest.java:79)
	at com.google.api.client.extensions.java6.auth.oauth2.AuthorizationCodeInstalledApp.authorize(AuthorizationCodeInstalledApp.java:82)
	at com.google.api.services.samples.dfareporting.DfaReportingFactory.authorize(DfaReportingFactory.java:74)
	at com.google.api.services.samples.dfareporting.DfaReportingFactory.getInstance(DfaReportingFactory.java:86)
	at com.google.api.services.samples.dfareporting.reports.DownloadFile.main(DownloadFile.java:52)

Please help  me out on this.

Thanks a lot in advance :)

**Comment by jimper** [comment]
Hi Anjan,

The error here isn't related to DCM, so I'm afraid I won't be able to help much. From the stack trace it looks like there may be some misconfiguration in your environment that's preventing connections (maybe a firewall or proxy problem?). You might have better luck asking around on the Google API Client Library for Java [support channels](https://developers.google.com/api-client-library/java/google-api-java-client/support).

Regards,
- Jonathon Imperiosi, DCM API Team

**Comment by anjanjena** [comment]
Hi Jonathan,

Thank for your suggestion.

Thank you so much for the quick response.

Regards,
Anjan
