### ISSUE TITLE
httperror 403 insufficient permissions in v4.0

### ISSUE THREAD

**Issue by matsuzaka-ryo** [googleads/googleads-dfa-reporting-samples#91]
Hi, I have a question of campaign manager API.  
I am trying to download a report file with Campaign manager API using [Python client library(v4)](https://github.com/googleads/googleads-dfa-reporting-samples/tree/main/python/v4).  

I followed [the documentation](https://developers.google.com/doubleclick-advertisers/getting_started?hl=en) to get credential.
After that, I ran the following and I could succeeded in authentication.

```
ryo@mypc:~/googleads-dfa-reporting-samples/python/v4$ python authenticate_using_user_account.py client_secrets.json
Found user profile with ID 9999999 and user name "ryo".
```

But after that, when I ran `python download_file.py 123456789 0987654321`, I got `insufficientPermissions` error.

```
ryo@mypc:~/googleads-dfa-reporting-samples/python/v4$ python download_file.py 123456789 0987654321
Traceback (most recent call last):
  File "/home/ryo/googleads-dfa-reporting-samples/python/v4/download_file.py", line 90, in <module>
    main(sys.argv)
  File "/home/ryo/googleads-dfa-reporting-samples/python/v4/download_file.py", line 54, in main
    report_file = service.files().get(reportId=report_id,fileId=file_id).execute()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryo/.cache/pypoetry/virtualenvs/googleads-dfa-reporting-samples-aytjwM6s-py3.11/lib/python3.11/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryo/.cache/pypoetry/virtualenvs/googleads-dfa-reporting-samples-aytjwM6s-py3.11/lib/python3.11/site-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://dfareporting.googleapis.com/dfareporting/v4/reports/123456789/files/0987654321?alt=json returned "Request had insufficient authentication scopes.". Details: "[{'message': 'Insufficient Permission', 'domain': 'global', 'reason': 'insufficientPermissions'}]">
```

Could you tell me what I missed or made mistakes?

Also, I found [the similar issue](https://github.com/googleads/googleads-dfa-reporting-samples/issues/16) but this information was old so did not help me. Thus asked the people about it.

**Comment by matsuzaka-ryo** [comment]
I could download report file with direct download method.


https://developers.google.com/doubleclick-advertisers/guides/download_reports?hl=en#direct_download
